server:
   port: 8091
   servlet:
       context-path: /messenger/

---



  spring:
    datasource:
       url: jdbc:postgresql://localhost:5432/messenger
       username: postgres
       password: Shkna1368
       platform: postgres

    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      database: POSTGRESQL
      hibernate:
       ddl-auto: update

---
   servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 15MB





